version: '3.7'
services:
  spinal-cord-toolbox-app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        VERSION: 1.0.0
      labels:
        org.label-schema.build-date: '2022-06-01T08:16:55Z'
        org.label-schema.schema-version: '1.0'
        org.label-schema.vcs-ref: f5f2eb9
        org.label-schema.vcs-url: git@github.com:elisabettai/spinal-cord-toolbox.git
        io.simcore.name: '{"name": "spinal-cord-toolbox-app"}'
        io.simcore.thumbnail: '{"thumbnail": "https://repository-images.githubusercontent.com/20361729/e268cd80-ad32-11e9-9faf-4cd1193b6144"}'
        io.simcore.description: '{"description": "Spinal Cord Toolbox (SCT) is a comprehensive,
          free and open-source set of command-line tools dedicated to the processing
          and analysis of spinal cord MRI data see (https://github.com/spinalcordtoolbox/spinalupport
          it provided (FSLeyes)."}'
        io.simcore.key: '{"key": "simcore/services/dynamic/spinal-cord-toolbox-app"}'
        io.simcore.version: '{"version": "1.0.0"}'
        io.simcore.integration-version: '{"integration-version": "2.0.0"}'
        io.simcore.type: '{"type": "dynamic"}'
        io.simcore.authors: '{"authors": [{"name": "Elisabetta Iavarone", "email":
          "iavarone@itis.swiss", "affiliation": "IT''IS Foundation"}]}'
        io.simcore.contact: '{"contact": "iavarone@itis.swiss"}'
        io.simcore.inputs: '{"inputs": {}}'
        io.simcore.outputs: '{"outputs": {}}'
        simcore.service.settings: '[{"name": "constraints", "type": "string", "value":
          ["node.platform.os == linux"]}, {"name": "Resources", "type": "Resources",
          "value": {"Limits": {"NanoCPUs": 4000000000, "MemoryBytes": 4294967296},
          "Reservations": {"NanoCPUs": 2000000000, "MemoryBytes": 2147483648}}}]'
    image: simcore/services/dynamic/spinal-cord-toolbox-app:1.0.0
  spinal-cord-toolbox-web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        VERSION: 1.0.0
      labels:
        org.label-schema.build-date: '2022-06-01T08:16:55Z'
        org.label-schema.schema-version: '1.0'
        org.label-schema.vcs-ref: f5f2eb9
        org.label-schema.vcs-url: git@github.com:elisabettai/spinal-cord-toolbox.git
        io.simcore.name: '{"name": "spinal-cord-toolbox-web"}'
        io.simcore.thumbnail: '{"thumbnail": "https://repository-images.githubusercontent.com/20361729/e268cd80-ad32-11e9-9faf-4cd1193b6144"}'
        io.simcore.description: '{"description": "Spinal Cord Toolbox (SCT) is a comprehensive,
          free and open-source set of command-line tools dedicated to the processing
          and analysis of spinal cord MRI data see (https://github.com/spinalcordtoolbox/spinalupport
          it provided (FSLeyes)."}'
        io.simcore.key: '{"key": "simcore/services/dynamic/spinal-cord-toolbox-web"}'
        io.simcore.version: '{"version": "1.0.0"}'
        io.simcore.integration-version: '{"integration-version": "2.0.0"}'
        io.simcore.type: '{"type": "dynamic"}'
        io.simcore.authors: '{"authors": [{"name": "Elisabetta Iavarone", "email":
          "iavarone@itis.swiss", "affiliation": "IT''IS Foundation"}]}'
        io.simcore.contact: '{"contact": "iavarone@itis.swiss"}'
        io.simcore.inputs: '{"inputs": {"input_1": {"displayOrder": 1.0, "label":
          "Input files", "description": "Files downloaded from service connected at
          the input", "type": "data:*/*"}}}'
        io.simcore.outputs: '{"outputs": {"output_1": {"displayOrder": 1.0, "label":
          "Output files", "description": "Files available for service connected to
          the output", "type": "data:*/*"}}}'
        simcore.service.compose-spec: '{"version": "3.7", "services": {"spinal-cord-toolbox-web":
          {"image": "$${SIMCORE_REGISTRY}/simcore/services/dynamic/spinal-cord-toolbox-web:$${SERVICE_VERSION}"},
          "spinal-cord-toolbox-app": {"image": "$${SIMCORE_REGISTRY}/simcore/services/dynamic/spinal-cord-toolbox-app:$${SERVICE_VERSION}"}}}'
        simcore.service.container-http-entrypoint: spinal-cord-toolbox-web
        simcore.service.restart-policy: no-restart
        simcore.service.paths-mapping: '{"inputs_path": "/home/scu/work/inputs", "outputs_path":
          "/home/scu/work/outputs", "state_paths": ["/home/scu/work/workspace"]}'
        simcore.service.settings: '[{"name": "constraints", "type": "string", "value":
          ["node.platform.os == linux"]}, {"name": "Resources", "type": "Resources",
          "value": {"Limits": {"NanoCPUs": 100000000, "MemoryBytes": 104857600}, "Reservations":
          {"NanoCPUs": 100000000, "MemoryBytes": 104857600}}}, {"name": "ports", "type":
          "int", "value": 28080}, {"name": "env", "type": "string", "value": ["APP_HOSTNAME=%%container_name.spinal-cord-toolbox-app%%"]}]'
    image: simcore/services/dynamic/spinal-cord-toolbox-web:1.0.0
